### ISSUE TITLE
Help to run compiled script from command line

### ISSUE THREAD

**Issue by rstormsf** [paul-hammant/MySikuliExample#4]
I run the Java project in NetBeans - it runs fine. Now, I wonder, how to run it from command line?
I guess, Netbeans can compile the code(using Build) command and produces `target` folder with jar SNAPSHOT, but I'm not able to run it
@paul-hammant - I'm mostly JavaScript/Ruby guy, so I might leak some of the knowledge that requires me to understand it. 
I was just curious how to write Sikuli script in java and run it from cli. 
Works fine in Jython/Jruby.

**Comment by rstormsf** [comment]
Please forgive me:

```
mvn exec:java -Dexec.mainClass="my.sikuli.example.MySikuliTest"
```

**Comment by paul-hammant** [comment]
No probs - its true though that Maven (and Java) are a little archaic when it comes to main-methods.
